### ISSUE TITLE
Migrate test and build scripts to separate directories

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#103]
See #86. Best practice is not to co-mingle the test, build, and deployment infrastructure with the Python files going into the wheel.

# Acceptance

* Only the files going into the Python package wheel are contained in `spatialprofilingtoolbox/`
* Test scripts and support infrastructure are fully contained in `test/`
* Build scripts, makefiles, and other support infrastructure are fully contained in `building/`

**Comment by CarlinLiao** [comment]
I want to rename `building/` to `build/` but it's already there so I guess...

**Comment by CarlinLiao** [comment]
Things I'm a bit confused about how to place:
* db/data_model. This is a bunch of SQL files and I can't dichotomize if they're used for wheel, build, or deployment. I don't think they go into the wheel?
* Ditto with .jinja files

**Comment by CarlinLiao** [comment]
I was so confused reading these Makefiles because I didn't realize what `.RECIPEPREFIX` did. I'd prefer more whitespace but I'll follow your convention here.

**Comment by CarlinLiao** [comment]
Slowly working through this... I think I have a good handle on how the makefiles behave now, and I'm getting a better grasp of what things are used (only?) during build. To solve this issue, we're to take all build scripts out of the main package directory, but identifying what's a build script and what isn't is suprisingly non-trivial.

From my view, here are the ambiguous cases:
* `entry_point` Python scripts are used only during build time to fill out the completions shell script template. Even so, it's dependent on anther `spatialprofilingtoolbox` module so it's not cleanly extractable. Resolving this might require review of pythonic best practice for handling python libraries that are meant to be run as their own independent CLI outside of a python CLI.
* `db/data_model` contains an `__init__.py` even though it only contains SQL files. As far as I can tell, these SQL files are only used at build time to coalesce them into a single `schema.sql` file. I think they should be moved to an outer `build` directory but maybe they get used during runtime as well?

What is the difference between build and runtime for SPT anyway? Running SPT is essentially for the purpose of spinning up (or "building") an SPT server right? So we build stuff to prepare for SPT to build its server. That's kinda confusing.

**Comment by CarlinLiao** [comment]
There's also the related matter of `schema.sql` being created in `db/data_model`, only to be mixed in to `initalize_schema.sql`. For now, I'm leaving `data_model` in the source directory and moving the location where `schema.sql` is built into the build directory, but we could clarify the structure here.

**Comment by CarlinLiao** [comment]
Emphasizing the `entry_point` point, `build_completions_script.py` assumes that the jinja template file and the output shell file are supposed to share a directory. One, two, or all three of these files should be moved into the build directory, but for now I'll keep it and the jinja file where it is, have it run from the build directory, and write the automade shell file to the build location.

**Comment by CarlinLiao** [comment]
Another sticking point: in the Dockerfile for `apiserver`, one line copies over the `./app` folder, which contains python source files. When build files are separated from source files, the app folder is now far away in the directory tree. How do we handle this?
1. Copy the app folder over temporarily
2. Adjust the Dockerfile calling args to find the faraway folder?
Either requires a change to a _general_ submodule build command to serve a _single_ submodule, apiserver. Presently, all other submodules build properly except apiserver due to this issue.

**Comment by jimmymathews** [comment]
Regarding `db/data_model` and jinja files:
All the SQL files are going into the wheel, they are used at runtime (mostly by the `spt db ...` commands). It's true that some of these are generated at build time. This is because the build process has to grab the schema from an external package. The `initialize_schema.sql` mishmash is a convenience file making the Python code calling up the SQL scripts simpler.
The file `spt-completion.sh.jinja` isn't needed in the wheel and can certainly be moved out! All other jinja files are located in `workflow` and are needed at runtime (`spt workflow configure ...`).

**Comment by jimmymathews** [comment]
I'd be happy to revert to whitespace in place of the non-standard RECIPEPREFIX, if you'd like.
The reason I adopted this is that the default prefix for the lines of each recipe, tab, makes it very difficult to tell the commands apart, especially when one command spans multiple lines. Within each recipe it is crucial to be able to tell the difference, because each command is run in its own shell (bash variables in one cannot reference variables in another).

**Comment by jimmymathews** [comment]
Regarding build vs runtime in this context:
I consider build time just the duration of building the Python package or Docker images.
Runtime is the duration of running commands installed with an installation of the Python package, or running a Docker container from one of the images.
Because of this expansive definition of runtime, lots of things are possibly required at runtime. SPT is meant to be the "toolbox" of all these things, no matter the context they are needed.

**Comment by jimmymathews** [comment]
Regarding `apiserver` `/app`: What's special about this case is that this module uses an external API server framework (FastAPI), which has its own pattern for how it looks for installed the handler code at server start time. I attempted to conform to this pattern.

**Comment by jimmymathews** [comment]
The entry_point business should be clarified a lot when I implement the fix to the "catch 22" / package introspection step.

**Comment by CarlinLiao** [comment]
`spt-completion.sh.jinja` is effectively part of `build_completions_script.py`, so it shouldn't be moved unless `build_completions_script.py` is as well. As far as I can tell, building the completions script is a build process and not a runtime one, so perhaps the files that do this should be moved to `building` AKA `build_scripts`. That said, their functionality is dependent on the "catch 22" so that might be a necessary prerequisite to resolve first.
