### ISSUE TITLE
test_proximity_core.py has inactive section with errors

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#126]
https://github.com/nadeemlab/SPT/blob/80d0fb219e26b888414fbb698e9948c85b8e6a43/test/workflow/tests/test_proximity_core.py#L101-L126

Observe here that `calc.do_aggregation_one_phenotype_pair` is provided 4 args, but in the definition of the function it requires 5 args. If this code ran as intended, it would error, but when we run `gmake test` it doesn't throw an error. This implies to me that the condition for this code block running, `TEST_PROXIMITY_WITH_PAIRS` is never set in the operating system environment. Is this intended?

**Comment by jimmymathews** [comment]
This is trace evidence of the following historical facts: A major change to the P2P workflow happened when I replaced code that precomputed distances for all pairs of cells (FOV-limited) with more efficient tree querying. But I wanted to make sure I was still getting the same answers. So I created this test, which I ran before and after the change, except the test itself was slightly different in the two cases. It worked, but I never deprecated the old version of the test, which I embedded in the same source file to be activated with that little environment switch.

I think this issue is resolved by deprecating the old test.

**Comment by jimmymathews** [comment]
The other thing is that this test doesn't actually run. There are a handful of tests that did not make the cut when real test-running was implemented. Making these run is part of #79 .

For this issue, let us also revisit `test_proximity_pipeline`:
1. Shorten the runtime by reducing the cell set that is used for calculation. (From 75s, perhaps down to 15s).
2. Increase the depth of consistency checks. Currently all that is checked is that the correct number of table records are created. We should check a certain number of metric values as well.

**Comment by jimmymathews** [comment]
Come to think of it, both tests will be updated with #83 , so let us just fold this issue into #83 .

**Comment by jimmymathews** [comment]
After #83 the proximity pipeline is very slimmed down, obsoleting this test.
