### ISSUE TITLE
Replace iteration over pandas dataframes where possible

### ISSUE THREAD

**Issue by CarlinLiao** [nadeemlab/SPT#175]
Per [StackOverflow](https://stackoverflow.com/questions/16476924/how-to-iterate-over-rows-in-a-dataframe-in-pandas/55557758#55557758) and pandas's own best practices, we should avoid using operations like `df.iterrows()` wherever possible, as they go against the vectorization qualities of pandas. Currently in SPT there are over 30 instances of `df.iterrows()` alone, and I think at least some of them can be changed to vector manipulations or at least list comprehensions instead of direct iterations.

I thought of this as I was writing a line to upload importance scores to the db. Following the example of other code in `db` as I understand them this is done line-by-line using INSERT, but [`df.to_sql()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sql.html) may be a better option if we have the proper connection object available.

This isn't something we need or even should do right now, but worth considering for any new code we write and then revisiting written code after we ship version 1.0.

**Comment by jimmymathews** [comment]
Hm good catch.

It seems that most of the occurrences of `DataFrame.iterrows` are concentrated in the elaborate import logic, in the same place as the linter warnings about branching and number of local variables. As far as performance goes, I'm not too worried about most occurrences because they deal with small data (phenotype lists, sample lists, etc.). But a few of the occurrences might be over cells or similar, I haven't checked closely. In this import logic it shows that we eschewed the use of an ORM. E.g. [here](https://github.com/nadeemlab/SPT/blob/1d6be92e5caaaad53d66f5f6ac21bf4a5d8f006c/spatialprofilingtoolbox/workflow/tabular_import/parsing/channels.py#L51). Most of it is re-inventing the wheel I'm sure.

I thought I encountered warnings about non-support of psycopg2 connections when I tried `DataFrame.to_sql` in the past, but that could be wrong.

For this issue, perhaps we could limit the scope to:
1. Assess the occurrences of `iterrows` for severity of possible performance consequences and refactorability.
2. Refactor for vectorization in the chosen cases.

**Comment by jimmymathews** [comment]
Note: Pandas officially only supports `to_sql` etc. using SQLAlchemy connections. The fact that it seems to work with a `psycopg2` connection in some places is kind of a fluke. Is it worth a dependency on SQLAlchemy in order to go between DataFrame and Postgres?

**Comment by CarlinLiao** [comment]
Per a quick web search, it seems like there are many examples of people using psycopg2 with to_sql successfully. I don't think official support should hold us back here, but this isn't something we should worry about until long down the road either.

**Comment by jimmymathews** [comment]
Note for clarity: In the elaborate import logic, refactoring for vectorization (and omitting `iterrows`) is non-trivial. The bulk of that work is a refactor task for the tabular import module.

**Comment by jimmymathews** [comment]
Many of these have been addressed, and the remaining occurrences of `iterrows` seem to be exclusively for small tables with low potential for benefit from vectorization.
