### ISSUE TITLE
Multiple files with same sample_identifier do not get aggregated

### ISSUE THREAD

**Issue by rvanguri** [nadeemlab/SPT#21]
This only applies to the phenotype proximity workflow. If there are multiple cell manifest files that have the same sample identifier (as indicated in the file manifest), they should be aggregated. The aggregation works appropriately over FOVs from a single cell manifest but if there is more than one the resulting database has multiple rows with the same source, target and sample identifier.

**Comment by jimmymathews** [comment]
The intermediate database `phenotype_proximity.db` is being used as a place for the jobs to concurrently send their output. Currently the division into jobs is by single files as a general default of SPT. So this database naturally gets different rows for different files, even though there is no "file identifier" column that advertises this fact.

1. It seems that you're making actual use of this intermediate database, so it is more than intermediate before the final results spreadsheet.
2. Even if you were not making independent use of it, I think you are saying that the final results spreadsheet is probably not doing exactly the right calculation if it is not first aggregating values for a given sample across multiple files. Checking on [`phenotype_proximity/integrator.py`](https://github.com/nadeemlab/SPT/blob/fadf0ac1a9df7aa178717182d11cc29fa816b4a8/spatialprofilingtoolbox/workflows/phenotype_proximity/integrator.py#L98), I have to agree.

I think the right modification is to add an initial step to the integrator (which is always a single-threaded operation intended to be run after all of the normal jobs have completed). This step would simply do a pass over `phenotype_proximity.db` to aggregate to a single row per (sample identifier, plus contextual parameters source phenotype, target phenotype, compartment, distance limit in pixels).

The question remains: What kind of aggregation should be performed? I think the idea to to remove the possibility of biasing results in favor of whatever occurs in samples with more files, so a simple arithemetic average of the cell pair count should suffice. (If this is not the right aggregation function, feel free to note that here.)

While I'm at it I will rename the legacy column name `cell_pair_count_per_FOV` to just `cell_pair_count`.

**Comment by jimmymathews** [comment]
It turns out this is the wrong kind of aggregation. It is expected that additional FOVs (or additional files with additional FOVs) may sometimes turn out to contain no useful information due to their location, and we do not want this situation to bring down any averages.

Moreover, we found that both the unaggregated and aggregated table might have some downstream utility. So now the plan is:

1. Leave the pre-aggregated table intact, consisting of per-job outputs.
2. Add to the pre-aggregated table the following columns: FOV index, and input file identifier, *and* source phenotype count, *and* target phenotype count (why not).
3. Create an aggregated version of the table at `spt-analyze-results` time, and save it separately. The main metric column should be a source-phenotype-count-weighted average whenever necessary (often this is not necessary, i.e. when there is only 1 FOV).

**Comment by jimmymathews** [comment]
This is implemented in the branch `issue21`, now merged. As described above, except:
1. FOV is not reported (already aggregated over FOVs as they appear in a single file).
2. Input filename is reported, not input file identifier (would need a little refactor otherwise).
3. Target phenotype count is not reported (not currently counted as part of the existing algorithm, so simpler to omit).
