### ISSUE TITLE
Linting and IDE setup

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#84]
Use an IDE, e.g. PyCharm or Visual Studio Code, to review and address compliance with conventions and to autodetect low-level bugs in the SPT codebase. After fixes the test suite should be run frequently to ensure continuity of behavior. Possibly, do any background work needed to make usage of the IDE the primary recommended mechanism for development.

## Acceptance

1. Commit a file containing the list of issues, plus "addressed" or "not addressed", to an issue branch.
2. If an IDE will be recommended, add a blurb about getting started with it to the developers' documentation

## Notes

A linter was not used very often during development, and neither was an IDE. This has most likely resulted in the occurrence of many small style errors, and perhaps larger real errors as well.

**Comment by CarlinLiao** [comment]
Working on this now. I'd add as development dependencies

* autopep8
* mypy
* pycodestyle
* pylint

to enforce this via pyproject. I think that this should make it PyCharm and VS Code independent, but I've only used VS Code for linting.

How involved would you like this resolution to be? #86 requests a full codebase review whereas linting can be as simple as
1. Applying whatever autopep8 does to each .py file
2. Manually fixing every error raised by a linter that can't be handled automatically, which includes but isn't limited to
   * Removing unused imports
   * Reordering imports to follow recommended style (standard, third-party, local)
   * Lines that are too long
   * Lack of type hints on functions
   * Missing docstrings on every method and class
   * Vague function names
3. (This isn't actually linting but) replacing full library imports with only importing the functions needed from the library

**Comment by jimmymathews** [comment]
This sounds perfect.
My work on #94 is touching a lot of the codebase, so maybe wait to do your initial pass via the automated tooling until `issue94` is merged.
You can update [maintenance.md](https://github.com/nadeemlab/SPT/blob/main/docs/maintenance.md) with instructions for getting the linting and IDE set up. Feel free to be very verbose there, I'm not too familiar with the formal conventions.

**Comment by CarlinLiao** [comment]
After discussion, we decided to
* spin out docstrings into a separate issue
* spin out type hints into a separate issue
* variable renames we'll consider to be out of scope
* this issue will be resolved by accomplishing the rest of the simple manual fixes in addition to the autopep8 changes

**Comment by CarlinLiao** [comment]
List of linter complaints that I'm not going to fix for this issue because they change functionality in addition to the above:
* (pylint)
   * prefer f-strings to `%` string formatting
   * use lazy `%` formatting in logging functions
   * `open` call doesn't specify encoding
   * constant name doesn't conform to UPPER CASE spelling style
   * redefine [variable name] from outer scope
   * complaint about the way an if statement is ordered
   * `!= None` -> `is not None`
   * consider iterating over a dict directly instead of calling keys()
   * unused variable
      * (in tuple returns where only some components are used)
      * (in a try-except)
      * (in a test)
      * (if it's the only line in a function)
   * consider using enumerate instead of range and len
   * consider iterating over a dict using items instead of over key lookups
   * variable name doesn't conform to snake_case
   * line too long in the case of a string that doesn't have an obvious breakpoint (e.g., URLs and regex, whereas SQL statements are easily breakable)
   * unused argument
   * anomalous backslash (on regex expressions)
   * hyphenated .py filenames instead of snake_case
   * imports not grouped (in the case of try/except imports not in the header of a file)
   * no exception type specified
   * dangerous default value ([], {}, etc.)
   * subprocess.run call doesn't explicitly set "check"
   * implictly defined variables in a class and for loop (e.g., check for one variable assures that another variable isn't unassigned)
   * super init not called
   * overriden child class function has more parameters than original
   * `assert condition == False` should be `is False` or `assert not` depending on if you're testing for exactly false or falsiness
   * unnecessary pass in abstract methods
   * using possibly unidentified loop variable
* mypy
   * function already defined (`get_phenotype_criteria` is defined thrice but is attached to a different flask endpoint each time)
   * define new function instead of assigning a lambda a variable name
   * defining class attribute outside of init
   * [class instance] has no [attribute] (when creating the new property by assigning to it)
   * argument has incompatible type (when calling a builtin function that is correctly type hinted with a user-defined variable that isn't)
   * incompatible type when assigning to a dict
* spellcheck: [many variable names] is not a word (although interventional is definitely not a word)
* me: I'm shocked that the linters don't complain about `while True`

Let me know if you'd like me to make these changes that the linters suggest @jimmymathews

**Comment by CarlinLiao** [comment]
Running tests now. Is "Checking for Docker credentials in ~/.docker.config.json" supposed to fail?

**Comment by jimmymathews** [comment]
Yeah I'm not concerned about the fact that these changes alter functionality, it seems like it they just need to be made.
There are a few I don't understand (e.g. it seems like a language flaw if [] or {} default values are "dangerous"...), but I'm sure they all have reasonable justifications.

**Comment by jimmymathews** [comment]
(The real reason that step is there is do enable the docker image push functionality, but I'm saying even if you aren't doing that it is useful to be "logged in".)

**Comment by CarlinLiao** [comment]
Going to leave this open for a little bit since there's that monster of a comment up there detailing things we probably want to spin into separate issues. How would you like to group them?

**Comment by CarlinLiao** [comment]
Fun fact: PEP 8 actually specifies 79 characters for line length (72 for long blocks of text), while pylint defaults to a more lenient 100.

**Comment by jimmymathews** [comment]
Hm yes that matches my memory, I thought I remembered an insanely short line length recommendation.

**Comment by jimmymathews** [comment]
I wonder if it makes sense to break it up by source file rather than by change type.
After tests are moved out, we could do 6 issues:

1. apiserver
2. db
3. workflow
4. countsserver
5. tests
6. anything else

**Comment by CarlinLiao** [comment]
#100 docstrings and type hinting addition has a similar file scope, but isn't structured as multiple issues. I think rolling it all up into one is fine.

**Comment by CarlinLiao** [comment]
I think this can be closed. We've recommended an IDE (or two) in `docs/style.md` and opened #105 to address linter complaints.
