### ISSUE TITLE
Codebase review, broad and shallow

### ISSUE THREAD

**Issue by jimmymathews** [nadeemlab/SPT#86]
This is a comprehensive review of the SPT repository codebase. After understanding the architecture, the deliverable is a list of bugs, design flaws, or obvious/simple improvements, including simplifications, ideally as new issues. The need for this is related to the fact that the vast majority of the current codebase was created by a single author and was not yet subjected to a review process.

Might be desirable to complete #84 as a prelude to this.

## Acceptance

- List of bugs, design flaws, obvious/simple improvements, checked in via some notes file on branch `issue86`.

**Comment by CarlinLiao** [comment]
A stray thought while messing with import orders: the codebase currently uses two or three ways to import SPT-related modules
1. `from spatialprofilingtoolbox...`
2. `from ..` (relative to current folder import)
3. `from SPT...`

I think this is partially because sometimes you're referring to the local installation of `spatialprofilingtoolbox`, and other times you're referring to an external pip installation. Add onto that the import from the module `SPT`, which if I recall correctly is the autocompletion package which is distinct from the `spatialprofilingtoolbox` installable from pip, and it gets kind of confusing.

If I understand this all correctly, I'd recommend redoing the import process so that
a. all imports are _explicit_ instead of _relative_, e.g., `from spatialprofilingtoolbox.db import foo` instead of `from ..db import foo`
b. convert `from SPT` imports to `from spatialprofilingtoolbox.autocompletion` or something of that ilk
c. make sure that a pip/external installation of `spatialprofilingtoolbox` is not required for the library to work properly

**Comment by jimmymathews** [comment]
I tried to systematically use `from spatialprofilingtoolbox...`, i.e. import from an installed package, exclusively in tests.
And `from ..module...` for relative imports in every package source file. I thought this was the normal way to do things; this was done specifically in order to achieve (c).

I don't think there is a way to do your suggestion (a). Explicit imports only work after the package is installed, right? That's a circular dependency of spatialprofilingtoolbox on itself. A violation of (c)?

The autocompletion script (i) needs to be distributed with the package, and (ii) needs to be built by a script that can import the package in order to autodiscover the various scripts. This is a catch-22 / circular depedency. To break this circle, I have the autocompletion script building happen in a quarantined area that only imports spatialprofilingtoolbox in a minimal way (obviously without the completion script). The usage (3) `from spt...` is import from a single-file module. This is sort of unclear from the name `spt`, because it seems like an alias for package `spatialprofilingtoolbox` which it is not. I think your (b) addresses this.

**Comment by jimmymathews** [comment]
Possibly I misunderstand what you mean by (c). I understand "software library" to mean an externally-provided package of some kind or another that is never asked to expose its implementation. If you want the "library to work properly" even if not packaged and installed, how can the libary be used at all under those conditions? Copying and pasting the source files into a new project? That seems like a violation of the library pattern in general.

**Comment by CarlinLiao** [comment]
Relative imports aren't the only way to import modules that share a top-level directory. In fact, absolute imports are recommended by pep8 due to the ambiguity of relative imports.

[See here for a better explanation,] but in short, `from ..submodule_name import b` is equivalent to `from module_name.submodule_name import b` if the name of your top level directory is `module_name`.

e.g., if your directory structure is
```
module_directory
 |- submodule_directory
 |    |- a.py
 |- b.py
main.py
```
in `b.py`, `import module_directory.submodule_directory.a` is equivalent to `import ..submodule_directory.a`. Only if the top level directory of `b.py` isn't `module_directory` will it start looking at packages installed from external sources.

**Comment by CarlinLiao** [comment]
[Also according to this resource, tests should live in a higher-level directory instead of proximal to the code it's testing.](https://py-pkgs.org/05-testing#test-structure) Given the volume of tests, it might be best to have a `test` directory at the same directory level as the `spatialprofilingtoolbox` directory, with an internal structure that mimics that of the `spatialprofilingtoolbox` directory. That said, I'm pretty sure you'd have to rework virtually all of your makefiles to accomodate this change.

Relatedly, when it comes to `import spt`, I think it's confusing that
1. there exists a single-file module that behaves independently of the spatialprofilingtoolbox library, and
2. that this single-file module is in a nested directory

I think it would be well served to move it outside along with the tests.

**Comment by jimmymathews** [comment]
Yeah maybe moving it to `building`, building is what it's for.
The only reason I didn't initially put tests out of the source tree and into their own tree was to avoid the possibility of mismatches accruing, between the directory structure in `spatialprofilingtoolbox` and the directory structure in `tests`. In fact, however, few of the tests are truly module-specific, so maybe they *shouldn't* match up.

**Comment by jimmymathews** [comment]
I will add an issue to pull out tests as you suggest (reminder, this issue is for review only and not meant to entail codebase alteration work). It shouldn't be that difficult to rework the directory structure, they are treated logically separately.

BTW I slightly lied above when I said that I used external imports of spatialprofilingtoolbox only in tests. I also systematically used them in scripts, treating the scripts as the library interface.

**Comment by CarlinLiao** [comment]
To follow python/PyPI conventions, the files in `spatialprofilingtoolbox/`should relate only to Python files that go into the library's wheel. The tests, docker file creation, and so on should exist outside of that directory.

Zeroing in on the `spt` CLI, I do notice that it is considered python code that's part of the spatialprofilingtoolbox package, as the pyproject.toml points to it as `spatialprofilingtoolbox.entry_point.spt:main_program`, while the `build_completions_script` imports it as its own independent library `from spt import get_commands`. Why doesn't `build_completions_script` say `from spatialprofilingtoolbox.entry_point.spt import get_commands` instead? I guess it's because it's a script that's not supposed to be installed as part of the library, but since it's what's building the strings returned by the CLI which is part of the library, it's a part of the library in by dependency. Are you sure this should be a script?

**Comment by jimmymathews** [comment]
Yeah, we should make separate issues for each of those things:
- Move tests and test comparison artifacts out
- Move Docker-related stuff out

I don't quite follow that last questions... Am I sure what should be a script? `build_completions_script.py`? It is not a script.
- `build_completions_script.py` builds a completions script (`build_completions_script.py` is not itself a script). The result is `spt-completion.sh` .
- The file `spt-completion.sh` should be distributed with the library.
- The file `build_completions_script.py` does not need to be distributed with the library. Could go into `building`.
- `spt.py` definitely contains Python code to be part of the library. It is the CLI entry point for every `spt ...` shell call.
- `build_completions_script.py` could do `from spatialprofilingtoolbox.entry_point.spt import get_commands` as you say. But if you are right about explicit imports, it does the same thing as `from spt import get_commands`, which is what it says now.

The whole trouble is this need for package introspection *in order to build the completions script*.  This is the catch-22 I described in an earlier comment. I understand the need to create library source artifacts without relying on the library itself, as a general rule, but I could not find a clean workaround.

**Comment by jimmymathews** [comment]
I think the underlying issue is the following.

`get_commands` is used in two ways
1. It is used at runtime by `spt.py` to figure out how to parse commands.
2. It is used to create the completions script comprising a part of the library.

In usage (1), it is important that `get_commands` only relies on the installed library, because `spt.py` entry point only has access to the installed library at runtime. That is why `importlib.resources` is used here.

But in usage (2), to break the circularity, it is important that `get_commands` does NOT rely on the installed library, but rather on whatever inspection of the package contents it can do before packaging has taken place.

It's fine to break it up into two functions, one for the purpose of `spt.py` and one for the purpose of `build_completions_script.py`, but it is *also* important for the two things to return the same results.

**Comment by jimmymathews** [comment]
I think this should be resolved with a static data artifact listing the module/command structure, plus a test that checks that the static artifact is consistent with the actual structure. Then the pre-packaging tool can refer to the static artifact.

**Comment by CarlinLiao** [comment]
And we should convert relative imports and standalone(?) imports (`from spt import ...`) to absolute imports.

I think that brings up the spinoff issues created to 4? Plus one more we may have only discussed verbally.
* Move tests and test comparison artifacts out
* Move Docker-related stuff out
* Resolve completions script catch-22
* Convert relative imports to absolute
* Rename/rework `workflow` directory to have more clear names and file structure (e.g., why is there a `workflows` folder in `workflow`)

There's also the long list of unresolved style issues in #84 plus typing and docstrings #100. Plenty of content for me to work on while you're on vacation! (Although it may not be very efficient for me to work on pulling out tests and Docker stuff, but I'll get/have to learn a lot about Docker, shell, and makefiles if you assign it to me.)

**Comment by CarlinLiao** [comment]
Also there's the `image_assets/` folder, which for a second I thought referred to Docker images but is actually using the word in the conventional sense.

**Comment by jimmymathews** [comment]
Those 5 look like the right list. Plus maybe the 6 linting issues I proposed.
Do you want to take a stab at writing the issue specs?

**Comment by CarlinLiao** [comment]
Now that I'm trying to write them, I don't think moving tests and Docker stuff in separate branches makes sense. The Docker stuff would need to updated twice: once after the tests are moved, then again when they themselves are moved. (Applies in either order.) I think we should combine them.

I think you should open the issues for the completions script catch-22 and `workflow/workflows`, you understand them much better than I do.

**Comment by CarlinLiao** [comment]
We want to move the Docker stuff and tests out, but all that stuff is compiled by the makefiles, but the makefiles will be obviated by the completion of #95. Do we still want to take the time to do this?

**Comment by CarlinLiao** [comment]
I've created issues for moving tests and Docker stuff out #103, converting imports in #102, linting errors and style issues #105, as well as typing/docstrings in #100. I haven't written them for the completions script catch-22 and redoing the `workflow` submodule for clarity as I don't fully understand those, can you open those @jimmymathews? Once those are done, we might be able to close this issue.

**Comment by jimmymathews** [comment]
#107 and #108 are now opened. Ready to close?
